# Generated by Django 4.0.4 on 2022-05-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamilia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
